const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const today = new Date();
const defaultDate = today.toISOString().slice(0, 10);
const bundledTimetable = 'assets/timetable-placeholder.jpeg';
const defaultDriveUrl = 'https://drive.google.com/drive/folders/1HMyNFdgA114v_yqhWk11BKCTS0CAu-4c?usp=sharing';
const supabaseConfig = window.SUPABASE_CONFIG || {};
const supabaseClient = window.supabase && supabaseConfig.url && supabaseConfig.anonKey && !/YOUR_|service_role|sb_secret/i.test(`${supabaseConfig.url} ${supabaseConfig.anonKey}`)
  ? window.supabase.createClient(supabaseConfig.url, supabaseConfig.anonKey)
  : null;
const store = {
  tasks: JSON.parse(localStorage.getItem('studyDeskTasks') || '[]'),
  finance: JSON.parse(localStorage.getItem('studyDeskFinance') || '[]'),
  settings: JSON.parse(localStorage.getItem('studyDeskSettings') || '{}'),
  timetable: localStorage.getItem('studyDeskTimetable') || bundledTimetable
};
let activeFilter = 'all';
let calendarDate = new Date(today.getFullYear(), today.getMonth(), 1);
let selectedDate = defaultDate;
let remoteMode = Boolean(supabaseClient);
let currentUser = null;
let authMode = 'login';

const thaiMonths = ['มกราคม','กุมภาพันธ์','มีนาคม','เมษายน','พฤษภาคม','มิถุนายน','กรกฎาคม','สิงหาคม','กันยายน','ตุลาคม','พฤศจิกายน','ธันวาคม'];
const shortMonths = ['ม.ค.','ก.พ.','มี.ค.','เม.ย.','พ.ค.','มิ.ย.','ก.ค.','ส.ค.','ก.ย.','ต.ค.','พ.ย.','ธ.ค.'];
const localDateKey = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const formatMoney = (amount) => `฿${Number(amount || 0).toLocaleString('th-TH', { maximumFractionDigits: 2 })}`;
const formatDate = (value) => { if (!value) return '-'; const d = new Date(`${value}T00:00:00`); return `${d.getDate()} ${shortMonths[d.getMonth()]} ${d.getFullYear() + 543}`; };
const save = () => { localStorage.setItem('studyDeskTasks', JSON.stringify(store.tasks)); localStorage.setItem('studyDeskFinance', JSON.stringify(store.finance)); localStorage.setItem('studyDeskSettings', JSON.stringify(store.settings)); };
const showToast = (message) => { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2400); };
function setAuthMessage(message, isError = false) { $('#authStatus').textContent = message; $('#authStatus').classList.toggle('error', isError); }
function showAuthScreen() { $('#authScreen').classList.remove('hidden'); $('.app-shell').classList.add('hidden'); remoteMode = false; }
function showDashboard(session) { currentUser = session.user; remoteMode = Boolean(supabaseClient); $('#authScreen').classList.add('hidden'); $('.app-shell').classList.remove('hidden'); $('#profileEmail').textContent = currentUser.email || 'บัญชีส่วนตัว'; $('#profileName').textContent = currentUser.email?.split('@')[0] || 'Workspace'; loadRemoteData(); }
function setAuthMode(mode) { authMode = mode; const signup = mode === 'signup'; $('#authEyebrow').textContent = signup ? 'CREATE WORKSPACE' : 'PRIVATE WORKSPACE'; $('#authTitle').textContent = signup ? 'สร้างบัญชี' : 'เข้าสู่ระบบ'; $('#authDescription').textContent = signup ? 'สร้างบัญชีเพื่อเก็บข้อมูลของคุณอย่างปลอดภัย' : 'เข้าสู่ระบบเพื่อดูข้อมูลส่วนตัวของคุณ'; $('#authSubmit').textContent = signup ? 'สมัครใช้งาน' : 'เข้าสู่ระบบ'; $('#authSwitch').textContent = signup ? 'มีบัญชีอยู่แล้ว? เข้าสู่ระบบ' : 'ยังไม่มีบัญชี? สมัครใช้งาน'; $('#authPassword').autocomplete = signup ? 'new-password' : 'current-password'; setAuthMessage(''); }
async function initAuth() { if (!supabaseClient) { showAuthScreen(); setAuthMessage('ไม่พบ Supabase config หรือ SDK', true); return; } const { data: { session } } = await supabaseClient.auth.getSession(); if (session) showDashboard(session); else showAuthScreen(); supabaseClient.auth.onAuthStateChange((_event, nextSession) => { if (nextSession) showDashboard(nextSession); else showAuthScreen(); }); }
$('#authSwitch').addEventListener('click', () => setAuthMode(authMode === 'login' ? 'signup' : 'login'));
$('#authForm').addEventListener('submit', async (event) => { event.preventDefault(); if (!supabaseClient) return; const email = $('#authEmail').value.trim(); const password = $('#authPassword').value; $('#authSubmit').disabled = true; setAuthMessage('กำลังดำเนินการ...'); const result = authMode === 'login' ? await supabaseClient.auth.signInWithPassword({ email, password }) : await supabaseClient.auth.signUp({ email, password }); $('#authSubmit').disabled = false; if (result.error) { setAuthMessage(result.error.message, true); return; } if (authMode === 'signup' && !result.data.session) setAuthMessage('สมัครสำเร็จ กรุณาตรวจอีเมลเพื่อยืนยันบัญชี'); else setAuthMessage('สำเร็จ'); });
$('#logoutButton').addEventListener('click', async () => { if (supabaseClient) await supabaseClient.auth.signOut(); });

function setSection(id) {
  $$('.page-section').forEach(section => section.classList.toggle('active', section.id === id));
  $$('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.section === id));
  const nav = $(`.nav-item[data-section="${id}"]`); $('#pageTitle').textContent = nav ? nav.textContent.trim() : 'ภาพรวม';
  $('#sidebar').classList.remove('open'); $('#backdrop').classList.remove('show'); window.scrollTo({ top: 0, behavior: 'smooth' });
  if (id === 'calendar') renderCalendar();
  if (id === 'finance') renderFinance();
}
$$('.nav-item[data-section], [data-jump]').forEach(button => button.addEventListener('click', () => setSection(button.dataset.section || button.dataset.jump)));
$('#openSidebar').addEventListener('click', () => { $('#sidebar').classList.add('open'); $('#backdrop').classList.add('show'); });
$('#closeSidebar').addEventListener('click', () => { $('#sidebar').classList.remove('open'); $('#backdrop').classList.remove('show'); });
$('#backdrop').addEventListener('click', () => { $('#sidebar').classList.remove('open'); $('#backdrop').classList.remove('show'); });

function openModal(type = 'task', date = defaultDate) {
  $('#modalBackdrop').classList.remove('hidden');
  $('#taskForm').classList.toggle('hidden', type !== 'task'); $('#financeForm').classList.toggle('hidden', type !== 'finance');
  $('#modalEyebrow').textContent = type === 'task' ? 'NEW TASK' : 'NEW TRANSACTION'; $('#modalTitle').textContent = type === 'task' ? 'บันทึกงานใหม่' : 'เพิ่มรายการการเงิน';
  if (type === 'task') { $('#taskDate').value = date; $('#taskTitle').focus(); } else { $('#financeDate').value = date; $('#financeTitle').focus(); }
}
function closeModal() { $('#modalBackdrop').classList.add('hidden'); }
$('#modalClose').addEventListener('click', closeModal); $('#modalBackdrop').addEventListener('click', (event) => { if (event.target === $('#modalBackdrop')) closeModal(); });
['quickAdd','emptyAdd','taskAdd','calendarAdd','dayAdd'].forEach(id => { const button = $(`#${id}`); if (button) button.addEventListener('click', () => openModal('task', id === 'dayAdd' ? selectedDate : defaultDate)); });
['financeAdd','transactionAdd'].forEach(id => { const button = $(`#${id}`); if (button) button.addEventListener('click', () => openModal('finance')); });

$('#taskForm').addEventListener('submit', async (event) => { event.preventDefault(); const task = { id: crypto.randomUUID(), title: $('#taskTitle').value.trim(), date: $('#taskDate').value, priority: $('#taskPriority').value, start: $('#taskStart').value, end: $('#taskEnd').value, note: $('#taskNote').value.trim(), done: false }; if (remoteMode) { const { data, error } = await supabaseClient.from('tasks').insert({ title: task.title, task_date: task.date, priority: task.priority, start_time: task.start || null, end_time: task.end || null, note: task.note || null, done: false, user_id: currentUser.id }).select().single(); if (error) { showToast(`บันทึกไม่สำเร็จ: ${error.message}`); return; } store.tasks.unshift(normalizeRemoteTask(data)); } else store.tasks.unshift(task); save(); closeModal(); event.target.reset(); renderAll(); showToast('บันทึกงานเรียบร้อยแล้ว'); });
$('#financeForm').addEventListener('submit', async (event) => { event.preventDefault(); const item = { id: crypto.randomUUID(), title: $('#financeTitle').value.trim(), amount: Number($('#financeAmount').value), type: $('#financeType').value, date: $('#financeDate').value }; if (remoteMode) { const { data, error } = await supabaseClient.from('finance_records').insert({ title: item.title, amount: item.amount, type: item.type, record_date: item.date, user_id: currentUser.id }).select().single(); if (error) { showToast(`บันทึกไม่สำเร็จ: ${error.message}`); return; } store.finance.unshift(normalizeRemoteFinance(data)); } else store.finance.unshift(item); save(); closeModal(); event.target.reset(); renderFinance(); updateStats(); showToast('บันทึกรายการเรียบร้อยแล้ว'); });

function taskMatches(task) { const search = $('#taskSearch').value.trim().toLowerCase(); return (activeFilter === 'all' || (activeFilter === 'done' ? task.done : !task.done)) && (!search || `${task.title} ${task.note}`.toLowerCase().includes(search)); }
function taskMeta(task) { return `${formatDate(task.date)}${task.start ? ` · ${task.start}${task.end ? ` - ${task.end}` : ''}` : ''}`; }
function renderTasks() {
  const tasks = store.tasks.filter(taskMatches); const list = $('#taskList');
  if (!tasks.length) { list.innerHTML = `<div class="empty-state"><div class="empty-icon">✓</div><strong>ไม่พบงานในรายการนี้</strong><span>เพิ่มงานใหม่หรือเปลี่ยนตัวกรอง</span></div>`; } else { list.innerHTML = tasks.map(task => `<div class="full-task-row"><button class="check-button ${task.done ? 'done' : ''}" data-toggle="${task.id}">${task.done ? '✓' : ''}</button><div><strong class="${task.done ? 'struck' : ''}">${escapeHtml(task.title)}</strong><small>${escapeHtml(task.note || 'ไม่มีรายละเอียด')}</small></div><span class="task-date">${taskMeta(task)}</span><span class="priority-label ${task.priority}">${{ high: 'สำคัญสูง', medium: 'ปานกลาง', low: 'ไม่เร่งด่วน' }[task.priority]}</span><button class="delete-button" data-delete="${task.id}" aria-label="ลบงาน">×</button></div>`).join(''); }
  $$('#taskList [data-toggle]').forEach(button => button.addEventListener('click', async () => { const task = store.tasks.find(item => item.id === button.dataset.toggle); const nextDone = !task.done; if (remoteMode) { const { error } = await supabaseClient.from('tasks').update({ done: nextDone }).eq('id', task.id); if (error) { showToast(`อัปเดตไม่สำเร็จ: ${error.message}`); return; } } task.done = nextDone; save(); renderAll(); }));
  $$('#taskList [data-delete]').forEach(button => button.addEventListener('click', async () => { if (remoteMode) { const { error } = await supabaseClient.from('tasks').delete().eq('id', button.dataset.delete); if (error) { showToast(`ลบไม่สำเร็จ: ${error.message}`); return; } } store.tasks = store.tasks.filter(item => item.id !== button.dataset.delete); save(); renderAll(); showToast('ลบงานแล้ว'); }));
}
$$('.filter-tab').forEach(button => button.addEventListener('click', () => { activeFilter = button.dataset.filter; $$('.filter-tab').forEach(item => item.classList.toggle('active', item === button)); renderTasks(); }));
$('#taskSearch').addEventListener('input', renderTasks);
function renderFocus() { const list = $('#focusList'); const pending = store.tasks.filter(task => !task.done).slice(0, 4); if (!pending.length) { list.className = 'task-list empty-state'; list.innerHTML = `<div class="empty-icon">✓</div><strong>ยังไม่มีงานที่บันทึกไว้</strong><span>เพิ่มงานแรกของคุณเพื่อเริ่มวางแผน</span><button class="small-button" id="emptyAddAgain">เพิ่มงาน</button>`; $('#emptyAddAgain').addEventListener('click', () => openModal()); return; } list.className = 'task-list'; list.innerHTML = pending.map(task => `<div class="task-row"><button class="check-button" data-focus-toggle="${task.id}"></button><div class="task-copy"><strong>${escapeHtml(task.title)}</strong><small>${taskMeta(task)}</small></div><i class="priority-dot ${task.priority}"></i></div>`).join(''); $$('#focusList [data-focus-toggle]').forEach(button => button.addEventListener('click', async () => { const task = store.tasks.find(item => item.id === button.dataset.focusToggle); if (remoteMode) { const { error } = await supabaseClient.from('tasks').update({ done: true }).eq('id', task.id); if (error) { showToast(`อัปเดตไม่สำเร็จ: ${error.message}`); return; } } task.done = true; save(); renderAll(); })); }
function renderUpcoming() { const list = $('#upcomingList'); const upcoming = [...store.tasks].filter(task => !task.done && task.date).sort((a,b) => a.date.localeCompare(b.date)).slice(0, 3); if (!upcoming.length) { list.className = 'agenda-list empty-state'; list.innerHTML = `<div class="empty-icon">▦</div><strong>ปฏิทินยังว่างอยู่</strong><span>งานที่มีวันกำหนดส่งจะแสดงตรงนี้</span>`; return; } list.className = 'agenda-list'; list.innerHTML = upcoming.map(task => `<div class="task-row"><div class="date-chip"><strong>${new Date(`${task.date}T00:00:00`).getDate()}</strong><small>${shortMonths[new Date(`${task.date}T00:00:00`).getMonth()]}</small></div><div class="task-copy"><strong>${escapeHtml(task.title)}</strong><small>${task.start || 'ไม่ระบุเวลา'} · ${task.priority === 'high' ? 'สำคัญสูง' : 'กำหนดส่ง'}</small></div></div>`).join(''); }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[char])); }
function normalizeRemoteTask(task) { return { id: task.id, title: task.title, date: task.task_date, priority: task.priority, start: task.start_time ? String(task.start_time).slice(0, 5) : '', end: task.end_time ? String(task.end_time).slice(0, 5) : '', note: task.note || '', done: task.done }; }
function normalizeRemoteFinance(item) { return { id: item.id, title: item.title, amount: Number(item.amount), type: item.type, date: item.record_date }; }
async function loadRemoteData() {
  if (!supabaseClient) return;
  const [{ data: tasks, error: tasksError }, { data: finance, error: financeError }] = await Promise.all([
    supabaseClient.from('tasks').select('*').order('task_date', { ascending: true }),
    supabaseClient.from('finance_records').select('*').order('record_date', { ascending: false })
  ]);
  if (tasksError || financeError) {
    remoteMode = false;
    const message = tasksError?.message || financeError?.message || 'ตรวจสอบตารางและ RLS Policy';
    showToast(`เชื่อม Supabase ไม่สำเร็จ: ${message}`);
    return;
  }
  store.tasks = (tasks || []).map(normalizeRemoteTask);
  store.finance = (finance || []).map(normalizeRemoteFinance);
  renderAll();
  renderFinance();
  showToast('โหลดข้อมูลจาก Supabase แล้ว');
}

function renderCalendar() { const year = calendarDate.getFullYear(), month = calendarDate.getMonth(); $('#monthTitle').textContent = `${thaiMonths[month]} ${year + 543}`; const first = new Date(year, month, 1).getDay(); const days = new Date(year, month + 1, 0).getDate(); let cells = ''; for (let i = 0; i < 42; i++) { const dayOffset = i - first + 1; const date = new Date(year, month, dayOffset); const dateKey = localDateKey(date); const inMonth = dayOffset > 0 && dayOffset <= days; const events = store.tasks.filter(task => task.date === dateKey && !task.done); cells += `<button class="calendar-cell ${inMonth ? '' : 'muted-day'} ${dateKey === selectedDate ? 'selected' : ''} ${dateKey === defaultDate ? 'today' : ''}" data-date="${dateKey}"><span class="day-number">${date.getDate()}</span>${events.slice(0,2).map(event => `<span class="calendar-event ${event.priority}">${escapeHtml(event.title)}</span>`).join('')}</button>`; } $('#calendarGrid').innerHTML = cells; $$('#calendarGrid [data-date]').forEach(cell => cell.addEventListener('click', () => { selectedDate = cell.dataset.date; renderCalendar(); })); renderSelectedDay(); }
function renderSelectedDay() { $('#selectedDateTitle').textContent = formatDate(selectedDate); const events = store.tasks.filter(task => task.date === selectedDate); const container = $('#dayEvents'); container.innerHTML = events.length ? events.map(task => `<div class="day-event"><strong>${escapeHtml(task.title)}</strong><span>${task.start ? `${task.start} - ${task.end || 'ไม่ระบุ'}` : 'ไม่ระบุเวลา'} · ${task.done ? 'เสร็จแล้ว' : 'ยังไม่เสร็จ'}</span></div>`).join('') : `<div class="empty-state"><div class="empty-icon">◷</div><span>วันนี้ยังไม่มีงาน</span></div>`; }
$('#prevMonth').addEventListener('click', () => { calendarDate.setMonth(calendarDate.getMonth() - 1); renderCalendar(); }); $('#nextMonth').addEventListener('click', () => { calendarDate.setMonth(calendarDate.getMonth() + 1); renderCalendar(); }); $('#goToday').addEventListener('click', () => { calendarDate = new Date(today.getFullYear(), today.getMonth(), 1); selectedDate = defaultDate; renderCalendar(); });

function calculateFreeTime() { const date = $('#freeDate').value || defaultDate; const [rangeStart, rangeEnd] = $('#freeRange').value.split('-').map(Number); const busy = store.tasks.filter(task => task.date === date && task.start && task.end && !task.done).map(task => ({ start: toMinutes(task.start), end: toMinutes(task.end), title: task.title })).sort((a,b) => a.start-b.start); const merged = []; busy.forEach(item => { const last = merged[merged.length - 1]; if (last && item.start <= last.end) last.end = Math.max(last.end,item.end); else merged.push({...item}); }); const slots = []; let cursor = rangeStart * 60; merged.forEach(item => { if (item.start > cursor) slots.push({ start: cursor, end: Math.min(item.start, rangeEnd * 60) }); cursor = Math.max(cursor, item.end); }); if (cursor < rangeEnd * 60) slots.push({ start: cursor, end: rangeEnd * 60 }); const available = slots.filter(slot => slot.end - slot.start >= 30); const total = available.reduce((sum, slot) => sum + slot.end - slot.start, 0); $('#freeResult').innerHTML = `<h3>${formatDate(date)} <span class="muted">· ว่างทั้งหมด ${Math.floor(total/60)} ชม. ${total%60 ? `${total%60} นาที` : ''}</span></h3><div class="time-bar">${Array.from({length: rangeEnd-rangeStart}, (_, index) => { const hour = (rangeStart+index)*60; const isBusy = merged.some(item => item.start < hour+60 && item.end > hour); return `<span class="time-block ${isBusy ? '' : 'free'}">${rangeStart+index}:00</span>`; }).join('')}</div>${available.length ? available.map(slot => `<div class="free-slot"><strong>${minutesToTime(slot.start)} - ${minutesToTime(slot.end)}</strong><span>เวลาว่าง ${Math.floor((slot.end-slot.start)/60)} ชม. ${((slot.end-slot.start)%60) ? `${(slot.end-slot.start)%60} นาที` : ''}</span></div>`).join('') : '<div class="empty-state"><span>ไม่มีช่วงเวลาว่างที่ยาวพอในช่วงนี้</span></div>'}`; }
const toMinutes = time => { const [h,m] = time.split(':').map(Number); return h*60+m; }; const minutesToTime = minutes => `${String(Math.floor(minutes/60)).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')}`; $('#calculateFree').addEventListener('click', calculateFreeTime); $('#freeDate').value = defaultDate;

$('#timetableInput').addEventListener('change', event => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { store.timetable = reader.result; localStorage.setItem('studyDeskTimetable', store.timetable); renderTimetable(); showToast('อัปโหลดตารางเรียนแล้ว'); }; reader.readAsDataURL(file); }); $('#removeTimetable').addEventListener('click', () => { store.timetable = bundledTimetable; localStorage.removeItem('studyDeskTimetable'); renderTimetable(); showToast('กลับไปใช้รูปตัวอย่างแล้ว'); }); function renderTimetable() { $('#uploadZone').classList.toggle('hidden', !!store.timetable); $('#timetablePreview').classList.toggle('hidden', !store.timetable); if (store.timetable) { $('#timetableImage').src = store.timetable; $('#removeTimetable').textContent = store.timetable === bundledTimetable ? 'เปลี่ยนรูปจริง' : 'กลับไปใช้รูปตัวอย่าง'; } }

function renderFinance() { const income = store.finance.filter(item => item.type === 'income').reduce((sum,item) => sum + item.amount,0); const expense = store.finance.filter(item => item.type === 'expense').reduce((sum,item) => sum + item.amount,0); $('#incomeTotal').textContent = formatMoney(income); $('#expenseTotal').textContent = formatMoney(expense); $('#balanceTotal').textContent = formatMoney(income-expense); const list = $('#transactionList'); list.innerHTML = store.finance.slice(0,5).map(item => `<div class="transaction"><div class="transaction-icon ${item.type}">${item.type === 'income' ? '↑' : '↓'}</div><div class="transaction-info"><strong>${escapeHtml(item.title)}</strong><small>${formatDate(item.date)}</small></div><span class="transaction-amount ${item.type}">${item.type === 'income' ? '+' : '-'}${formatMoney(item.amount)}</span></div>`).join('') || `<div class="empty-state"><span>ยังไม่มีรายการการเงิน</span></div>`; drawChart(); }
function drawChart() { const svg = $('#financeChart'); const data = [...store.finance].sort((a,b) => a.date.localeCompare(b.date)).slice(-7); const values = data.map(item => item.type === 'income' ? item.amount : -item.amount); const max = Math.max(...values.map(Math.abs), 100); const points = values.length ? values.map((value,index) => `${45 + (index * (650 / Math.max(values.length-1,1)))},${130 - (value / max) * 95}`) : '45,130 150,112 255,145 360,88 465,106 570,60 675,83'; const pointsArray = typeof points === 'string' ? points.split(' ') : points; const polyline = Array.isArray(pointsArray) ? pointsArray.join(' ') : points; const area = `${polyline} 675,230 45,230`; svg.innerHTML = `<line class="chart-grid-line" x1="45" y1="35" x2="675" y2="35"/><line class="chart-grid-line" x1="45" y1="130" x2="675" y2="130"/><line class="chart-grid-line" x1="45" y1="230" x2="675" y2="230"/><text class="chart-label" x="4" y="39">สูง</text><text class="chart-label" x="13" y="134">0</text><text class="chart-label" x="2" y="234">ต่ำ</text><polygon class="chart-area" points="${area}"/><polyline class="chart-line" points="${polyline}"/>${pointsArray.map((point,index) => { const [x,y] = point.split(','); return `<circle class="chart-point" cx="${x}" cy="${y}" r="4"/><text class="chart-label" text-anchor="middle" x="${x}" y="250">${data[index] ? new Date(`${data[index].date}T00:00:00`).getDate() : index+1}</text>`; }).join('')}`; }

function loadSettings() { $('#driveUrl').value = store.settings.driveUrl || defaultDriveUrl; $('#calendarUrl').value = store.settings.calendarUrl || ''; const configured = supabaseConfig.url && supabaseConfig.anonKey && !/YOUR_|service_role|sb_secret/i.test(`${supabaseConfig.url} ${supabaseConfig.anonKey}`); $('#supabaseStatus').textContent = configured ? 'ตั้งค่า Supabase แล้วจาก supabase-config.js' : 'ยังไม่ได้ตั้งค่า supabase-config.js'; }
$('#saveDrive').addEventListener('click', () => { store.settings.driveUrl = $('#driveUrl').value.trim(); save(); showToast('บันทึกลิงก์ Google Drive แล้ว'); }); $('#saveCalendar').addEventListener('click', () => { store.settings.calendarUrl = $('#calendarUrl').value.trim(); save(); showToast('บันทึกลิงก์ปฏิทินแล้ว'); });
function openExternal(setting, fallback) { const url = store.settings[setting] || fallback; window.open(url, '_blank', 'noopener'); }
$('#driveButton').addEventListener('click', () => openExternal('driveUrl', defaultDriveUrl)); $('#driveCardButton').addEventListener('click', () => openExternal('driveUrl', defaultDriveUrl)); $('#googleCalendar').addEventListener('click', () => openExternal('calendarUrl', 'https://calendar.google.com/calendar/u/0/r'));
function updateStats() { const pending = store.tasks.filter(task => !task.done).length; const income = store.finance.filter(item => item.type === 'income').reduce((sum,item) => sum + item.amount,0); const expense = store.finance.filter(item => item.type === 'expense').reduce((sum,item) => sum + item.amount,0); $('#statTasks').textContent = pending; $('#statIncome').textContent = formatMoney(income); $('#statExpense').textContent = `รายจ่าย ${formatMoney(expense)}`; $('#statEvents').textContent = new Set(store.tasks.filter(item => item.date && item.date.startsWith(`${today.getFullYear()}-${String(today.getMonth()+1).padStart(2,'0')}`)).map(item => item.date)).size; }
function renderAll() { renderTasks(); renderFocus(); renderUpcoming(); renderCalendar(); updateStats(); }
$('#todayLabel').textContent = today.toLocaleDateString('th-TH', { weekday:'long', day:'numeric', month:'long', year:'numeric' }); $('#heroDate').textContent = String(today.getDate()).padStart(2,'0'); $('.date-card small').textContent = `${shortMonths[today.getMonth()]} ${today.getFullYear()+543}`;
loadSettings(); renderTimetable(); renderAll(); renderFinance(); calculateFreeTime(); initAuth();
